name: pgcontainer
version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: local-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: praveen
      POSTGRES_PASSWORD: praveen10
      POSTGRES_DB: local
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
